package me.lo.lomefree.Interfaces;


public interface RRCodes
{
    int DBX_CHOOSER_REQUEST = 11;
    int READ_IMAGE_REQUEST_CODE = 33;
    int VERIFY_KEY_REQUEST = 44;
    int REQUEST_CODE = 55;
    int KEY_FILE_REQUEST_CODE = 66;
    int QR_KEY_REQUEST_CODE = 77;
    int SINGLE_KEY_FILE_RESULT_CODE = 88;
    int MULTI_KEY_FILE_RESULT_CODE = 99;
    int QR_KEY_RESULT_CODE = 100;
    int BAD_PIN_RESULT = 111;
    int SAVE_FOLDER_GET_FILE_REQUEST = 122;
    int OPEN_MEDIA_PICKER = 133;
    int PROGRESS_ACTIVITY_REQUEST = 144;
    int PROGRESS_ACTIVITY_MULTIPLE_ERRORS = 155;
    int KEY_SHARE_REQUEST_CODE = 166;
    int PICK_FILEANDDIR_REQUEST_CODE = 177;
    int SINGLE_FILE_REQUEST_CODE = 188;
    int SINGLE_DIR_REQUEST_CODE = 199;
    int IMPORT_KEY_DB_REQUEST_CODE = 211;
    int RSA_KEY_REQUEST_CODE = 233;
    int MULTI_FILE_REQUEST_CODE = 244;
    int DESTROY_TASK_REQUEST_CODE = 255;
}
